In [95]:
#import Libraries
import numpy as np
import pandas as pd

In [96]:
#read csv
df = pd.read_csv("train_blackFriday.csv")
df

User_ID Product_ID Gender    Age  Occupation City_Category  \
0       1000001  P00069042      F   0-17          10             A   
1       1000001  P00248942      F   0-17          10             A   
2       1000001  P00087842      F   0-17          10             A   
3       1000001  P00085442      F   0-17          10             A   
4       1000002  P00285442      M    55+          16             C   
...         ...        ...    ...    ...         ...           ...   
550063  1006033  P00372445      M  51-55          13             B   
550064  1006035  P00375436      F  26-35           1             C   
550065  1006036  P00375436      F  26-35          15             B   
550066  1006038  P00375436      F    55+           1             C   
550067  1006039  P00371644      F  46-50           0             B   

       Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                               2               0                   3   
1                               2               0                   1   
2                               2               0                  12   
3                               2               0                  12   
4                              4+               0                   8   
...                           ...             ...                 ...   
550063                          1               1                  20   
550064                          3               0                  20   
550065                         4+               1                  20   
550066                          2               0                  20   
550067                         4+               1                  20   

        Product_Category_2  Product_Category_3  Purchase  
0                      NaN                 NaN      8370  
1                      6.0                14.0     15200  
2                      NaN                 NaN      1422  
3                     14.0                 NaN      1057  
4                      NaN                 NaN      7969  
...                    ...                 ...       ...  
550063                 NaN                 NaN       368  
550064                 NaN                 NaN       371  
550065                 NaN                 NaN       137  
550066                 NaN                 NaN       365  
550067                 NaN                 NaN       490  

[550068 rows x 12 columns]

In [97]:
#number of rows and coulmns
df.shape

(550068, 12)

In [98]:
#show data types found
df.dtypes

User_ID                         int64
Product_ID                     object
Gender                         object
Age                            object
Occupation                      int64
City_Category                  object
Stay_In_Current_City_Years     object
Marital_Status                  int64
Product_Category_1              int64
Product_Category_2            float64
Product_Category_3            float64
Purchase                        int64
dtype: object

In [99]:
#show coulmns
df.columns

Index(['User_ID', 'Product_ID', 'Gender', 'Age', 'Occupation', 'City_Category',
       'Stay_In_Current_City_Years', 'Marital_Status', 'Product_Category_1',
       'Product_Category_2', 'Product_Category_3', 'Purchase'],
      dtype='object')

In [100]:
#Checking NaN values in the given dataset
df.isna().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [101]:
#Checking duplicate values in the dataset
df.duplicated().sum()

0

In [102]:
#Renaming the column name to lower case
df.columns = [x.lower() for x in df.columns]
df.columns

Index(['user_id', 'product_id', 'gender', 'age', 'occupation', 'city_category',
       'stay_in_current_city_years', 'marital_status', 'product_category_1',
       'product_category_2', 'product_category_3', 'purchase'],
      dtype='object')

In [103]:
#Removing Reducant Values (user id)
df.drop(columns=['user_id'], inplace=True)

In [104]:
#Checking for unique values in each individual column of the dataset
df.nunique()

product_id                     3631
gender                            2
age                               7
occupation                       21
city_category                     3
stay_in_current_city_years        5
marital_status                    2
product_category_1               20
product_category_2               17
product_category_3               15
purchase                      18105
dtype: int64

In [105]:
#replace each range in age coulmn to its creosspond category ex:0-17 ->child ,18-25 ->teenage, 26-50 -> adult , 51-55+ ->old

In [106]:
df["age"].value_counts()

age
26-35    219587
36-45    110013
18-25     99660
46-50     45701
51-55     38501
55+       21504
0-17      15102
Name: count, dtype: int64

In [107]:
df["age"] = df["age"].replace({"0-17": "child", 
                               "18-25": "teenage", 
                               "26-35": "adult", 
                               "36-45": "adult", 
                               "46-50": "adult", 
                               "51-55": "old", 
                               "55+": "old"})

In [108]:
df["age"].value_counts()

age
adult      375301
teenage     99660
old         60005
child       15102
Name: count, dtype: int64

In [109]:
#Checking for unique values for city_years column
df["stay_in_current_city_years"].nunique()

5

In [110]:
#remove + from rows in city_years column

In [111]:
df["stay_in_current_city_years"].value_counts()

stay_in_current_city_years
1     193821
2     101838
3      95285
4+     84726
0      74398
Name: count, dtype: int64

In [112]:
df["stay_in_current_city_years"] = df["stay_in_current_city_years"].str.strip('+')

In [113]:
df["stay_in_current_city_years"]

0         2
1         2
2         2
3         2
4         4
         ..
550063    1
550064    3
550065    4
550066    2
550067    4
Name: stay_in_current_city_years, Length: 550068, dtype: object

In [114]:
#Checking for unique values for category_1 column
df["product_category_1"].unique()

array([ 3,  1, 12,  8,  5,  4,  2,  6, 14, 11, 13, 15,  7, 16, 18, 10, 17,
        9, 20, 19], dtype=int64)

In [115]:
#Checking for unique values for category_2 column
df["product_category_2"].unique()

array([nan,  6., 14.,  2.,  8., 15., 16., 11.,  5.,  3.,  4., 12.,  9.,
       10., 17., 13.,  7., 18.])

In [116]:
#fill null you found
mode_value = df["product_category_2"].mode()[0]
df["product_category_2"] = df["product_category_2"].fillna(mode_value) 

In [117]:
#Checking for unique values for category_3 column
df["product_category_3"].unique()

array([nan, 14., 17.,  5.,  4., 16., 15.,  8.,  9., 13.,  6., 12.,  3.,
       18., 11., 10.])

In [118]:
#fill null you found
mode_value = df["product_category_3"].mode()[0]
df["product_category_3"] = df["product_category_3"].fillna(mode_value) 

In [119]:
df["product_id"].unique()

array(['P00069042', 'P00248942', 'P00087842', ..., 'P00370293',
       'P00371644', 'P00370853'], dtype=object)

In [120]:
#check for null values
df.isna().sum()

product_id                    0
gender                        0
age                           0
occupation                    0
city_category                 0
stay_in_current_city_years    0
marital_status                0
product_category_1            0
product_category_2            0
product_category_3            0
purchase                      0
dtype: int64

In [121]:
#check for duplicates values
df.duplicated().sum()

201